development:
  adapter: mysql2
  host: localhost
  database: meuhorario_dev
  pool: 5
  username: meuhorario
  password: UbdTL3XB

test:
  adapter: mysql2
  host: localhost
  database: meuhorario_test
  pool: 5
  username: meuhorario
  password: UbdTL3XB

production:
  adapter: mysql2
  host: <%= ENV["DB_IP"] %>
  port: <%= ENV["DB_PORT"] %>
  database: meuhorario_production
  pool: 5
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>
